OCEAN_WIDTH = 50
OCEAN_HEIGHT = 50

MAX_SHARK_ENERGY = 100
MIN_SHARK_MOVE_ENERGY = 20
MIN_SHARK_REPRODUCTION_ENERGY = 40
SHARK_REPRODUCTION_PROBABILITY = 0.2
SHARK_CREATION_PROBABILITY = 0.05


MAX_SARDINE_ENERGY = 30
MIN_SARDINE_MOVE_ENERGY = 1
MIN_SARDINE_REPRODUCTION_ENERGY = 5
SARDINE_CREATION_PROBABILITY = 0.3
